-- ============================================================================
-- Flyway baseline (V1) — the complete schema as it stands on Neon on 2026-07-04.
--
-- Generated from `pg_dump --schema-only` of the live database and cleaned (psql
-- meta-commands and session SET noise removed). This is the authoritative schema:
--   * a FRESH database (dev / CI / a new environment) is built entirely by this file;
--   * the EXISTING Neon database is *baselined* at V1 (Flyway marks it applied WITHOUT
--     running it — see spring.flyway.baseline-on-migrate), so this never re-runs there.
--
-- Do NOT edit this file after it has been applied anywhere. Schema changes go in a
-- new V2__*.sql (V3__*.sql, ...) migration.
-- ============================================================================

-- ---- Tables --------------------------------------------------------------

CREATE TABLE public.departments (
    id bigint NOT NULL,
    contact_email character varying(255),
    dept_name character varying(255) NOT NULL,
    dept_code character varying(255) NOT NULL,
    version bigint DEFAULT 0
);

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.exam_cycles (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone,
    exam_month_year character varying(255),
    name character varying(255) NOT NULL,
    academic_year integer DEFAULT 0 NOT NULL,
    term character varying(255)
);

ALTER TABLE public.exam_cycles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_cycles_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.login_throttle (
    throttle_key character varying(255) NOT NULL,
    attempts integer NOT NULL,
    locked_until timestamp(6) with time zone
);

CREATE TABLE public.registration_events (
    id bigint NOT NULL,
    action character varying(255),
    actor character varying(255),
    actor_role character varying(255),
    note character varying(500),
    reg_id character varying(255),
    "timestamp" timestamp(6) with time zone,
    CONSTRAINT chk_registration_events_action CHECK (((action)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT chk_registration_events_actor_role CHECK (((actor_role)::text = ANY ((ARRAY['STUDENT'::character varying, 'ADMIN'::character varying, 'PRINCIPAL'::character varying, 'HOD'::character varying, 'DEPT_OFFICE'::character varying])::text[])))
);

ALTER TABLE public.registration_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registration_events_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.registration_subjects (
    reg_id character varying(255) NOT NULL,
    subject_id bigint NOT NULL
);

CREATE TABLE public.registrations (
    reg_id character varying(255) NOT NULL,
    registered_at timestamp(6) without time zone,
    status character varying(255),
    roll_no character varying(255),
    id bigint NOT NULL,
    verified_by character varying(255),
    snap_branch character varying(255),
    snap_email character varying(255),
    snap_name character varying(255),
    snap_phone character varying(255),
    snap_semester integer,
    snap_year_of_joining integer,
    version bigint,
    exam_cycle_id bigint NOT NULL,
    snap_academic_year integer,
    CONSTRAINT chk_registrations_status CHECK (((status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);

ALTER TABLE public.registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registrations_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.student_semester_terms (
    id bigint NOT NULL,
    academic_year integer NOT NULL,
    roll_no character varying(255) NOT NULL,
    semester integer NOT NULL
);

ALTER TABLE public.student_semester_terms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_semester_terms_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.students (
    roll_no character varying(255) NOT NULL,
    branch character varying(255),
    current_semester integer NOT NULL,
    email character varying(255),
    name character varying(255),
    phone character varying(255),
    year_of_joining integer NOT NULL,
    date_of_birth date,
    entry_semester integer DEFAULT 1 NOT NULL
);

CREATE TABLE public.subject_eligible_departments (
    subject_id bigint NOT NULL,
    dept_id bigint NOT NULL
);

CREATE TABLE public.subjects (
    id bigint NOT NULL,
    semester integer NOT NULL,
    subject_name character varying(255),
    dept_id bigint,
    course_code character varying(255),
    credits integer DEFAULT 0 NOT NULL,
    subject_type character varying(255),
    academic_year_offered integer DEFAULT 0 NOT NULL,
    CONSTRAINT chk_subjects_subject_type CHECK (((subject_type)::text = ANY ((ARRAY['REGULAR'::character varying, 'ELECTIVE'::character varying])::text[])))
);

ALTER TABLE public.subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subjects_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.users (
    username character varying(255) NOT NULL,
    password character varying(255),
    role character varying(255),
    dept_id bigint,
    must_change_password boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_users_role CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'PRINCIPAL'::character varying, 'HOD'::character varying, 'DEPT_OFFICE'::character varying])::text[])))
);

-- ---- Primary keys & unique constraints -----------------------------------

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.exam_cycles
    ADD CONSTRAINT exam_cycles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.login_throttle
    ADD CONSTRAINT login_throttle_pkey PRIMARY KEY (throttle_key);

ALTER TABLE ONLY public.registration_events
    ADD CONSTRAINT registration_events_pkey PRIMARY KEY (id);

-- NOTE: registrations PK is on reg_id (not the entity @Id `id`, which is a plain
-- GENERATED IDENTITY column). Historical; load-bearing — see db-schema-change-rules.
ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT registrations_pkey PRIMARY KEY (reg_id);

ALTER TABLE ONLY public.student_semester_terms
    ADD CONSTRAINT student_semester_terms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (roll_no);

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (username);

ALTER TABLE ONLY public.student_semester_terms
    ADD CONSTRAINT uk_student_semester UNIQUE (roll_no, semester);

-- Hibernate-generated name for the dept_code unique (kept verbatim so validate matches).
ALTER TABLE ONLY public.departments
    ADD CONSTRAINT uka98yj7l53srcy6e08grm1tw90 UNIQUE (dept_code);

-- Redundant with registrations_pkey (both unique on reg_id); kept for parity.
ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT uq_registrations_reg_id UNIQUE (reg_id);

-- ---- Indexes (incl. partial-unique business rules) -----------------------

CREATE UNIQUE INDEX uq_exam_cycles_name ON public.exam_cycles USING btree (name);

-- at most one active exam cycle
CREATE UNIQUE INDEX uq_exam_cycles_single_active ON public.exam_cycles USING btree (active) WHERE (active = true);

-- at most one pending (SUBMITTED) registration per (student, cycle)
CREATE UNIQUE INDEX uq_pending_reg_per_cycle ON public.registrations USING btree (roll_no, exam_cycle_id) WHERE ((status)::text = 'SUBMITTED'::text);

-- one offering of a course per academic year
CREATE UNIQUE INDEX uq_subjects_code_year ON public.subjects USING btree (course_code, academic_year_offered);

-- ---- Foreign keys --------------------------------------------------------

ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT fk69oiykyuu1vw227bguc1wdavr FOREIGN KEY (exam_cycle_id) REFERENCES public.exam_cycles(id);

ALTER TABLE ONLY public.registration_events
    ADD CONSTRAINT fk_registration_events_reg_id FOREIGN KEY (reg_id) REFERENCES public.registrations(reg_id);

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT fkagcibl3s2punqkd7e3shuct9c FOREIGN KEY (dept_id) REFERENCES public.departments(id);

ALTER TABLE ONLY public.subject_eligible_departments
    ADD CONSTRAINT fkbw6mvyjk0yc5lhow97de4qw0b FOREIGN KEY (dept_id) REFERENCES public.departments(id);

ALTER TABLE ONLY public.subject_eligible_departments
    ADD CONSTRAINT fkelabgxscouqw0no41fmkfm4q1 FOREIGN KEY (subject_id) REFERENCES public.subjects(id);

ALTER TABLE ONLY public.registration_subjects
    ADD CONSTRAINT fkk6e8w8e2wdqm87eusb3kddca0 FOREIGN KEY (reg_id) REFERENCES public.registrations(reg_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkny8a9c8evadqjfx8jvetc73gs FOREIGN KEY (dept_id) REFERENCES public.departments(id);

ALTER TABLE ONLY public.registration_subjects
    ADD CONSTRAINT fkssr1w3t17rhy0c3q4epowu3rt FOREIGN KEY (subject_id) REFERENCES public.subjects(id);

ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT fktgn40ul7ir2551h1t090myxs7 FOREIGN KEY (roll_no) REFERENCES public.students(roll_no);
