-- ============================================================================
-- V9 — bulk progression audit: one header row per run, one row per student.
--
-- Bulk progression advances students.current_semester by 2 for a whole cohort
-- in a single UPDATE. That statement is otherwise unreconstructible: it leaves
-- no trace on any student row (the timeline in student_semester_terms is seeded
-- at creation and is deliberately NOT touched by bulk progression — a second
-- timeline writer is what makes progression disagreement possible). These two
-- tables ARE the record, written in the same transaction as the UPDATE, the
-- same way registration_events is written with a status flip.
--
-- Sizing: one row per affected student per run, so a whole-college run is
-- ~20k rows (<1 MB). Written by INSERT ... SELECT so the rows never leave
-- Postgres; a run is 4 statements regardless of student count.
--
-- roll_no is a PLAIN COLUMN, not an FK to students, on purpose. The audit row
-- must outlive the student: an FK would either block a later delete or cascade
-- the history away. Same reasoning as the registration snapshot columns.
--
-- Both tables ARE mapped JPA entities (ProgressionBatch, ProgressionBatchStudent),
-- so columns must match the mapping (ddl-auto=validate). The CHECKs, FK and
-- indexes are DB-level guards only, invisible to validate — same convention as
-- the rest of the schema.
-- ============================================================================

CREATE TABLE public.progression_batches (
    id bigint NOT NULL,
    actor_username character varying(255) NOT NULL,
    run_at timestamp(6) with time zone NOT NULL,
    filter_semester integer,
    filter_dept_code character varying(255),
    promoted_count integer NOT NULL,
    excluded_count integer NOT NULL,
    skipped_count integer NOT NULL,
    CONSTRAINT pk_progression_batches PRIMARY KEY (id),
    -- null = "all semesters"; otherwise the run was narrowed to one even semester
    CONSTRAINT chk_progression_batches_filter_semester
        CHECK (filter_semester IS NULL OR (filter_semester IN (2, 4, 6, 8)))
);

ALTER TABLE public.progression_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progression_batches_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.progression_batch_students (
    id bigint NOT NULL,
    batch_id bigint NOT NULL,
    roll_no character varying(255) NOT NULL,
    semester_from integer NOT NULL,
    -- null for every non-PROMOTED outcome: nothing moved, so there is no "to"
    semester_to integer,
    outcome character varying(255) NOT NULL,
    CONSTRAINT pk_progression_batch_students PRIMARY KEY (id),
    CONSTRAINT fk_progression_batch_students_batch
        FOREIGN KEY (batch_id) REFERENCES public.progression_batches(id) ON DELETE CASCADE,
    CONSTRAINT chk_progression_batch_students_outcome CHECK (((outcome)::text = ANY ((ARRAY[
        'PROMOTED'::character varying,
        'EXCLUDED_BY_ADMIN'::character varying,
        'SKIPPED_AT_MAX'::character varying,
        'SKIPPED_INVALID_SEMESTER'::character varying])::text[]))),
    -- a promotion always moves +2 and always lands on an even semester; anything
    -- else records no destination. Catches an arithmetic slip at the DB level.
    CONSTRAINT chk_progression_batch_students_semester_to CHECK (
        ((outcome)::text = 'PROMOTED'::text AND semester_to = semester_from + 2)
        OR ((outcome)::text <> 'PROMOTED'::text AND semester_to IS NULL))
);

ALTER TABLE public.progression_batch_students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progression_batch_students_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- PARTIAL, and deliberately so. The table is lopsided: a whole-college run writes ~20k PROMOTED
-- rows and a few hundred of everything else, and BOTH queries the app issues want only the
-- everything-else side (the batch-detail read, and the excluded-count taken inside the write
-- transaction). A plain (batch_id) index would make each of them walk all 20k rows of the batch
-- and then sort. This is ~200x smaller to maintain, which matters because the maintenance happens
-- inside the promotion transaction.
CREATE INDEX idx_progression_batch_students_batch_notpromoted
    ON public.progression_batch_students (batch_id, outcome, roll_no)
    WHERE outcome <> 'PROMOTED';

-- No index on roll_no: nothing queries per-student history yet. Adding one costs ~20k extra index
-- entries per run to serve no reader. Add it WITH the screen that needs it.

-- history list is newest-first
CREATE INDEX idx_progression_batches_run_at
    ON public.progression_batches (run_at DESC);
